### ISSUE TITLE
Either breakpoint or EIP acting weirdly

### ISSUE THREAD

**Issue by Sinderella** [x64dbg/x64dbg#1630]
Details
* x32dbg (21 June 2017)
* Windows Server 2003 R2 32 bits

I am trying to replicate an exploit by overwriting SEH, so I put I a breakpoint on the address I want it to point to, as shown below:

<img width="299" alt="screen shot 2017-06-23 at 06 37 39" src="https://user-images.githubusercontent.com/1926450/27468152-0c342772-57e0-11e7-96e9-656f5d550165.png">

I run my PoC, SEH is overwritten:

<img width="258" alt="screen shot 2017-06-23 at 06 40 15" src="https://user-images.githubusercontent.com/1926450/27468176-346008ec-57e0-11e7-81f4-c56f4f78d612.png">

Once the app is stuck, I pressed Shift + F9 and hopefully it would stop at the breakpoint. It didn't and end up at the address below that.

<img width="469" alt="screen shot 2017-06-23 at 06 41 45" src="https://user-images.githubusercontent.com/1926450/27468219-8075a4d0-57e0-11e7-929b-b56f78b0eb22.png">

I thought it's fine, I should still be able to step over for instruction by instuction. I pressed F8 once, and it ends up like this:

<img width="471" alt="screen shot 2017-06-23 at 06 42 37" src="https://user-images.githubusercontent.com/1926450/27468247-a681b240-57e0-11e7-888b-fa1b1bb1b582.png">

It wasn't executing the return instruction, the application crashed and other exception handler is thrown. The PoC was working fine on Immunity debugger.

**Comment by mrexodia** [comment]
Try using a hardware breakpoint to see if the problem is related to software breakpoints only.

**Comment by Sinderella** [comment]
If I use the hardware breakpoint, it stopped at `0x6D396948`, but I still cannot do a single step. I gave me the following error:

```
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 0
           ExceptionCode: 80000004 (EXCEPTION_SINGLE_STEP)
          ExceptionFlags: 00000008
        ExceptionAddress: 6D396948 jvm.6D396948
        NumberParameters: 0
Last chance exception on 6D396948 (80000004, EXCEPTION_SINGLE_STEP)!
```

Please let me know if you need more information.
