### ISSUE TITLE
Run / Step (Pass exceptions) doesn't actually pass the exception to the executable [x32]

### ISSUE THREAD

**Issue by mgostIH** [x64dbg/x64dbg#1685]
X32 DBG doesn't proceed a divide by zero exception (Neither swallowing or passing exception)

- Debugger version : Aug 11 2017
- Operating system: Windows 7 64 bits
- Came to a `xor eax, eax   /    div eax` asm, can't proceed without setting origin outside the code.
- After getting to this exception, x32dbg will log this:
```
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 1
           ExceptionCode: C0000094 (EXCEPTION_INT_DIVIDE_BY_ZERO)
          ExceptionFlags: 00000000
        ExceptionAddress: 001A1355 jacrackme.001A1355
        NumberParameters: 0
First chance exception on 001A1355 (C0000094, EXCEPTION_INT_DIVIDE_BY_ZERO)!
```
But won't make me overcome it with a shift+F7/F8/F9 or by directly using the GUI for stepping and passing exceptions.

![poc div eax](https://user-images.githubusercontent.com/13892786/29253430-45fb96d4-806c-11e7-91e4-b3f7233be636.PNG)

No plugins installed other than Scylla (Default install)

Hope the issue is clear enough!
